title: Fariha Nowshin
subtitle: Computer Science Student
logo: logo1.jpeg
description: Data Science Enthusiast interested in machine learning, deep learning, and turning messy data into clear decisions.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
baseurl: "/1156_Fariha_Portfolio"
url: "https://faarihaa.github.io"
